spring:
  jpa:
    hibernate:
      ddl_auto: update
    show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3356/evaluation?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver